[package]
name = "wasm_insquare"
version = "0.1.0"
authors = ["Jens Kristian Vyff <kristianvyff@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.58"
serde = "1.0.111"
serde_json = "1.0"